### ISSUE TITLE
cannot be compiled in vs2010

### ISSUE THREAD

**Issue by xebecnan** [GRGSIBERIA/EAWebKit#1]
I tried to compile it from "Project\VC2010\EAWebKit_VC2010.sln" in vs2010, but ends up with lots of errors.
For example:
'char16_t' redefinition; different basic types
'OutputDebugStringW' : cannot convert parameter 1 from 'char [2049]' to 'LPCWSTR'
'GetProcAddress' : cannot convert parameter 2 from 'const wchar_t [13]' to 'LPCSTR'

**Comment by GRGSIBERIA** [comment]
You gave parameters is the character literal.
Your sources gave you an answer :)

HINT:
Long Pointer Const Wide STRing : typedef LPCWSTR const wchar_t_;
Long Point Const STRing : typedef LPCSTR const char_;
